title: Liam-Hsieh-toolbox
site_author: Liam Hsieh 
team_name: Advanced Optimization and Decision Science
team_page: team.md
#remote_theme: carlosperate/jekyll-theme-rtd


#remote_theme: just-the-docs/just-the-docs
#remote_theme: ryanmcdermott/jekyll-latex
markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax: true


mermaid:
#   # Version of mermaid library
#   # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
   version: "9.1.6"
  
# exclude: 
#   - assets/css/*

