title: Liam-Hsieh-toolbox
site_author: Liam Hsieh 
team_name: Advanced Optimization and Decision Science
team_page: team.md
#remote_theme: carlosperate/jekyll-theme-rtd

#insert links.html to above nav.html in base.html
links_section: false

markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax: true


mermaid:
#   # Version of mermaid library
#   # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/ and ensure it matches js version we used
   version: "9.1.6"
  
# exclude: 
#   - assets/css/*

