title: title
site_author: Liam Hsieh 
site_url: https://intel-sandbox.github.io/decision-science
team_name: Advanced Optimization and Decision Science

#remote_theme: carlosperate/jekyll-theme-rtd

#insert links.html to above nav.html in base.html
links_section: false

edit_on_github: false

markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax: true


mermaid:
   version: "9.1.6"
  
# exclude: 
#   - assets/css/*

